create_section("a/v?q=Z2l0aHViLmNvbQ==", "img1", "Github");
create_section("a/v?q=dnNjb2RlLmRldg==", "img13", "VS Code");
create_section("a/v?q=d2luMTEuYmx1ZWVkZ2UubWU=", "img2", "Windows 11 in React");
create_section("a/v?q=eHAucXVlbnEuY29tLw==", "img3", "Windows XP");
create_section("a/v?q=Y2hhdGdwdC5jb20=", "img4", "ChatGPT");
// create_section("apps/view?q=d3d3LnR3aXRjaC50dg==", "/main/files/assets/twitch-img.png", "Twitch");
create_section("a/v?q=ZGlzY29yZC5jb20=", "img5", "Discord");
create_section("a/v?q=b3Blbi5zcG90aWZ5LmNvbQ==", "img6", "Spotify");
create_section("a/v?q=cGxleC50dg==", "img7", "Plex");
create_section("a/v?q=ZnJlZWRucy5hZnJhaWQub3Jn", "img8", "FreeDNS");
create_section("a/v?q=ZXh0cHJpbnQzci5naXRodWIuaW8vcHJpbnRlci5odG1s", "img9", "Extprint3r");
create_section("a/v?q=dGhlaG9tZXdvcmthaS5jb20=", "img10", "The Homework AI");
create_section("a/v?q=bWF0aC1ncHQub3Jn", "img11", "MathGPT");
create_section("a/v?q=cXVpbGxib3QuY29t", "img12", "Quillbot");
// create_section("/bots", "/main/files/assets/bot.png", "Bot Spammers (WIP)");